# Gitleaks configuration for CiviCue
# https://github.com/gitleaks/gitleaks

[extend]
useDefault = true

[allowlist]
description = "generated artifacts & test fixtures"
regexes = [
    '''src/generated/.*''',
    '''fingerprints/.*''',
    '''tests/fixtures/.*''',
    '''(.*/)?__fixtures__/.*''',
    '''.*\.snap$'''
]

# Redact secrets in output logs
redact = true