# Gitleaks configuration for CiviCue
# This configuration enables secret scanning with redaction and path exclusions

# Redact secrets in logs for security
redact = true

# Allowlist paths to exclude from scanning
[allowlist]
paths = [
    # Generated files
    "src/generated/",
    
    # Fingerprints directory
    "fingerprints/",
    
    # Test fixtures
    "test/fixtures/",
    ".*/fixtures/",
    
    # Build/dist directories
    "dist/",
    "build/",
    
    # Node modules
    "node_modules/",
    
    # Logs
    "logs/",
    ".*\\.log$"
]

# Use default gitleaks rules
# Rules can be customized here if false positives occur