name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  verify:
    name: Verify (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ "20.x" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install (frozen lockfile)
        run: pnpm -s install --frozen-lockfile

      - name: Typecheck
        run: pnpm -s typecheck

      - name: Lint
        run: pnpm -s lint:ci

      - name: Arch Tests
        run: pnpm -s test:arch

      - name: Unit Tests
        run: pnpm -s test:all

      - name: Build
        run: pnpm -s build

      - name: Validate SF Socrata Registry
        if: |
          contains(github.event_name, 'pull_request') && (
            contains(github.event.head_commit.modified, 'municipalities/CA/SF/directory.json') ||
            contains(github.event.head_commit.modified, 'scripts/build-datasf-index.mjs') ||
            contains(github.event.head_commit.modified, 'scripts/validate-datasf-index.mjs') ||
            contains(github.event.head_commit.modified, '__docs__/catalogs/sf-socrata-profile.md')
          )
        run: |
          if [ -f "municipalities/CA/SF/directory.json" ]; then
            pnpm -s run registry:socrata:sf:validate
          else
            echo "Directory file not found, skipping validation"
          fi