name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  verify:
    name: Verify (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ "20.x" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install (frozen lockfile)
        run: pnpm -s install --frozen-lockfile

      - name: Typecheck
        run: pnpm -s typecheck

      - name: Lint
        run: pnpm -s lint:ci

      - name: Arch Tests
        run: pnpm -s test:arch

      - name: Unit Tests
        run: pnpm -s test:all

      - name: Build
        run: pnpm -s build