name: OpenAPI Lint and Type Generation

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  validate-openapi:
    name: Validate OpenAPI and Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install (frozen lockfile)
        run: pnpm -s install --frozen-lockfile

      - name: Lint OpenAPI (fail on warnings)
        run: pnpm openapi:lint:ci

      - name: Generate and verify types are up-to-date
        run: pnpm openapi:check

      - name: Run type-level tests
        run: pnpm tsd

      - name: Typecheck all code
        run: pnpm typecheck